language: node_js
node_js:
<<<<<<< HEAD
- '0.10'
before_install:
- openssl aes-256-cbc -K $encrypted_aeeaf3e3325c_key -iv $encrypted_aeeaf3e3325c_iv
  -in .ftppass.enc -out .ftppass -d
- npm install -g grunt-cli
before_script:
- npm install -g bower
- bower install
=======
  - '0.10'
before_install:
  - npm install -g grunt-cli
before_script:
  - npm install -g bower
  - bower install
  
>>>>>>> e23f8cf64255632ec1a8df6cbd9d296fa52071b7
